Update test
fitbody/jr-frontend-challenge pull request #1
Opened 2021-05-05 23:28 UTC by mfigueroapa

2021-05-05 23:38 UTC, MOsorioC requested changes

2021-05-05 23:38 UTC, MOsorioC commented on README.md
> +> **Note:** For this challenge you'll have to use ReactJs or VueJs. You can also use design libraries such as [Ant Design](https://ant.design), [Material-UI](https://material-ui.com), [React bootstra
```suggestion
> **Note:** For this challenge you must use ReactJs or VueJs. Also you can use design libraries such as [Ant Design](https://ant.design), [Material-UI](https://material-ui.com), [React bootstrap](https://react-bootstrap.github.io), among others.
```

2021-05-05 23:38 UTC, MOsorioC commented on README.md
> +You'll have to consume the following REST API: [The Rick and Morty API](https://rickandmortyapi.com)
```suggestion
You must consume the following REST API: [The Rick and Morty API](https://rickandmortyapi.com)
```

2021-05-06 03:05 UTC, MOsorioC approved these changes

2021-05-06 14:48 UTC, Alexis-dev-web approved these changes

2021-05-06 15:09 UTC, merged